### ISSUE TITLE
This is ass, what is a good obfuscator source?

### ISSUE THREAD

**Issue by ghost** [Dentrax/Z00bfuscator#1]
LMAO this is ass it doesn't protect the actual code just adds/changes a few names.

Please link a good obfuscator source, unlike this and Confuser ex

**Comment by Dentrax** [comment]
I guess you didn't read the README file. :)

There are no _good obfuscator_. All of them are easily to reversible for such a managed-compiled languages. Use a native language with enterprise level *custom* virtualization and packer programs. Do not use public obfuscators too.

**Comment by hugzho** [comment]
Alright man, what steps should I take to make my own obfuscator? I really want to
