### ISSUE TITLE
.Net Core 2.0.0 is Deprecated

### ISSUE THREAD

**Issue by E-Acosta** [Dentrax/Z00bfuscator#2]
Hello, I think the tool is awesome but, i can't use in some new projects because dotnet core 2.0.0 it's deprecated, is it possible upgrade to almost 3.1.10 version (LTS)?

**Comment by Dentrax** [comment]
Since I dropped using C# a few years ago, I'm afraid I don't have much time to do that. But I would be glad if you send a PR to upgrade to that version. :)
